### ISSUE TITLE
Prime Next Episode

### ISSUE THREAD

**Issue by danilovicente** [aminomancer/Netflix-Marathon-Pausable#1]
I added those lines to auto skip to the next episode in amazon prime video

`                else if ((store = this.byCls("countdown")[0]))
                    // skip next ep
                    this.clk(store);
`

**Comment by aminomancer** [comment]
it already skips the countdown, why add another one? `this.qry(".atvwebplayersdk-nextupcard-button")`

if that's not already working for you, can you give me some details about your environment? browser, operating system, region and language? if amazon's presenting a different version of the player for different locales, that may be the cause.
