### ISSUE TITLE
Doesn't work on Disney+

### ISSUE THREAD

**Issue by spudpiggy** [aminomancer/Netflix-Marathon-Pausable#12]
Show is Bluey. I am British so using the UK version of the site. This may be related to the Skip Intro button only showing when I restart or go back 10 seconds.

**Comment by aminomancer** [comment]
Thanks for the report. I don't have a Disney+ subscription anymore so I can't test it at the moment, but I'm happy to accept a PR that fixes this bug. Otherwise someone can send me their Disney+ login at u060i2aqv@mozmail.com
