### ISSUE TITLE
Follows ads at end of Prime videos

### ISSUE THREAD

**Issue by xcasxcursex** [aminomancer/Netflix-Marathon-Pausable#14]
When you watch a movie on Prime Video, as the credits roll, they give you a 'next up' button to another movie. Basically, it's an ad. This script follows it as it uses all the same elements as TV episodes do. 

There's an easy fix though, since there is an element (several, but this one seems best) that only exists on TV episodes, so you can do something like:

`      if (this.isVis("dv-web-player") && this.qry("#tab-selector-episodes")) {` 

on line 372. Works here, I hope this helps :)

**Comment by aminomancer** [comment]
Fixed by 2a10033.
Thanks for reporting
