### ISSUE TITLE
ads for other series and movies at the end of each episode.

### ISSUE THREAD

**Issue by jumoog** [aminomancer/Netflix-Marathon-Pausable#4]
The German Amazon plays at the end of each series episode an advertisement for a series or movie before you are allowed to watch the next episode. You can skip the commercial by clicking on "Überspringen".

🇩🇪  "Überspringen"  -> 🇺🇸  "Skip"
![grafik](https://user-images.githubusercontent.com/5268791/136102008-f8a881b4-eee9-435c-b935-6f8e145ce7ec.png)

**CSS Path**
`html.a-js.a-audio.a-video.a-canvas.a-svg.a-drag-drop.a-geolocation.a-history.a-webworker.a-autofocus.a-input-placeholder.a-textarea-placeholder.a-local-storage.a-gradients.a-transform3d.a-touch-scrolling.a-text-shadow.a-text-stroke.a-box-shadow.a-border-radius.a-border-image.a-opacity.a-transform.a-transition.a-ember body.a-m-de.a-aui_72554-c.a-aui_accordion_a11y_role_354025-c.a-aui_killswitch_csa_logger_372963-t1.a-aui_launch_cardui_a11y_fix_346896-t1.a-aui_launch_expander_ally_fix_354901-t1.a-aui_markup_disabled_link_btn_351411-t1.a-aui_pci_risk_banner_210084-c.a-aui_popover_trigger_add_role_350993-t1.a-aui_preload_261698-c.a-aui_rel_noreferrer_noopener_309527-c.a-aui_template_weblab_cache_333406-c.a-aui_tnr_v2_180836-c.atfimgloaded div#dv-web-player.dv-player-fullscreen div.webPlayerContainer div div.webPlayerElement div.webPlayerSDKContainer div.webPlayerSDKUiContainer div.webPlayerUIContainer div.atvwebplayersdk-player-container.fvjm8ow.f1d62f50 div.f1bwtfkz div.fnk6wk div.atvwebplayersdk-overlays-container.fdsrz54.f1sp4gm7 div.fkhz08q.f8hspre div.atvwebplayersdk-bottompanel-container.f1ha12bn.f177tia9.fc1n9o1.f25z3of.floz2gv.f1ak3391 div.fmugii2.atvwebplayersdk-infobar-container div.ffzg8ke.f989gul div.fe39tpk div.fu4rd6c.f1cw2swo`

**CSS Selector**
`.fu4rd6c`

![grafik](https://user-images.githubusercontent.com/5268791/136103213-49e515dc-00ec-4107-b884-d1ba9f287eae.png)

**Comment by aminomancer** [comment]
Try 5.2.1 and let me know if you find anything else

**Comment by jumoog** [comment]
It works but i'm using "Überspringen" because the class names looks generated and will change soon or later
