### ISSUE TITLE
does not click play next on Disney plus when an episode ends

### ISSUE THREAD

**Issue by Razzad819** [aminomancer/Netflix-Marathon-Pausable#8]
code change on line 399 to ```else if ((store = this.qry(`button[data-testid="up-next-play-button"]`))) {``` seems to fix the problem?

**Comment by aminomancer** [comment]
Think you might be confused about line number or version or something? 399 is not disney plus

**Comment by Razzad819** [comment]
script version 5.4.1 this is what it gives me in the tampermonkey edit view
![Screenshot](https://user-images.githubusercontent.com/110964217/183877118-4c4af254-ee2c-4a80-bee6-4eaaa095958e.png)

**Comment by aminomancer** [comment]
Okay thanks I see what you mean. Looks like they stopped exposing that prop as a DOM attribute. I added your change to version 5.4.3
